version: '3.8'
services:
  scala:
    image: hseeberger/scala-sbt:11.0.12_1.5.5_2.13.6
    container_name: scala
    working_dir: /app
    volumes:
      - .:/app           
    ports:
      - "9000:9000"
    command: tail -f /dev/null
